defmodule Facebex.Model.Member do

	defstruct id: nil,
	  administrator: nil,
	  about: nil,
	  address: nil,
	  age_range: nil,
	  bio: nil,
	  birthday: nil,
	  context: nil,
	  currency: nil,
	  devices: [],
	  education: [],
	  email: nil,
	  favorite_athletes: nil,
	  favorite_teams: nil,
	  first_name: nil,
	  gender: nil,
	  hometown: nil,
	  inspirational_people: [],
	  install_type: nil,
	  installed: nil,
	  intested_in: nil,
	  is_shared_login: nil,
	  is_verified: nil,
	  languages: [],
	  last_name: nil,
	  link: nil,
	  location: nil,
	  locale: nil,
	  meeting_for: [],
	  middle_name: nil,
	  name: nil,
	  name_format: nil,
	  payment_pricepoints: nil,
	  test_group: nil,
	  political: nil,
	  relationship_status: nil,
	  religion: nil,
	  security_settings: nil,
	  significant_other: nil,
	  sports: nil,
	  suggested_groups: nil,
	  quotes: nil,
	  third_party_id: nil,
	  timezone: nil,
	  token_for_business: nil,
	  updated_time: nil,
	  shared_login_upgrade_required_by: nil,
	  verified: nil,
	  video_upload_limits: nil,
	  viewer_can_send_gift: nil,
	  website: nil,
	  work: [],
	  cover: nil

end